layout_spectrum: 0.6914608778897673
typography_spectrum: 0.8010023871902376
color:
  brandColors:
    - '#292929'
    - '#5B7876'
    - '#8F9E8B'
    - '#F2E6B6'
    - '#412A22'
  brandStrength: 0.5599303101189435
  lightness: 0.4064595305826515
  saturation: 0.41804673010483384
  rhythmicContrast: 0.4639685172587633
github: true
opengraph:
  image: null
  type: null
  appId: null
analytics:
  google: null
  facebook: null
  twitter: null
author:
  name: Neal G. Moore
  email: neal@nealmoore.com
  url: www.nealmoore.com
logo: null
name: Moore Media Services
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: About me
    url: 'http://about.me/nealmoore'
    type: external
favicon: null
title: We love great storytelling!
description: writing / editing / video
purpose:
  - type: contact
    url: 'mailto:neal@nealmoore.com'
    label: Contact me
  - type: external
    url: 'http://about.me/nealmoore'
    label: About me
