typography_spectrum: 0.7224477799609303
color:
  brandColors:
    - '#FFFFFF'
    - '#97D0E3'
    - '#396572'
    - '#589FB1'
    - '#8B1200'
  brandStrength: 0.8611211113166064
  lightness: 0.05508910049684346
  saturation: 0.40554935159161687
  rhythmicContrast: 0.047331958543509245
github: true
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.3594215812627226
analytics:
  google: null
  facebook: null
  twitter: null
name: mms
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: About me
    url: 'http://about.me/nealmoore'
    type: external
favicon: null
title: Moore Media Services
description: writing / editing / video
purpose:
  - type: contact
    url: 'mailto:neal@nealmoore.com'
    label: Contact me
  - type: external
    url: 'http://about.me/nealmoore'
    label: About me
